version: "3.8"

services:
  app:
    build: .
    container_name: save-bulgaria-app
    ports:
      - "8080:8080" # Maps localhost:8080 → container:8080
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/save_bulgaria_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - db # Ensures db service starts before app
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: save-bulgaria-db
    environment:
      POSTGRES_DB: save_bulgaria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432" # Optional: expose PostgreSQL to your host machine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
