services:
  - type: web
    name: save-bulgaria-api
    env: docker         # <-- this forces Docker mode
    region: frankfurt   # or oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://your-db-host:5432/save_bulgaria_db
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: 123
