spring:
  server:
    port: ${PORT:8080}
  datasource:
    url: jdbc:postgresql://dpg-d1qhlher433s73ed8dtg-a.oregon-postgres.render.com/save_bulgaria_db
    username: save_bulgaria_db_user
    password: wdSvfPXocQuOmxShjdxuiWCnD1zELOOM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: save-bulgaria

google:
  oauth2:
    client-id: 688975825427-m6mjn358n71bqeo3cfs77ucjplmt2v03.apps.googleusercontent.com

logging:
  level:
    com.peter.save_bulgaria: INFO
    org.springframework.security: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/save-bulgaria.log

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always